In [ ]:
import tensorflow as tf
print("Version of tensorflow is : ",tf.__version__)
import numpy as np

In [3]:
model = tf.keras.models.Sequential(tf.keras.layers.Dense(1 , input_shape = (1,)))
variables = model.variables
variables

[<tf.Variable 'dense_1/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.6564964]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [4]:
print("Shape of kernal : ",variables[0].shape)
print("Shape of bias   : ",variables[1].shape)

Shape of kernal :  (1, 1)
Shape of bias   :  (1,)


In [7]:
print("Value of kernal : ",variables[0].numpy())
print("Value of bias   : ",variables[1].numpy())

Value of kernal :  [[0.6564964]]
Value of bias   :  [0.]


**Create own Tensors**

---

One Dimensional Tensors

In [10]:
tensor_1_1 = tf.Variable("Hello World!" , dtype=tf.string)
tensor_1_2 = tf.Variable(5 , dtype=tf.int32)
tensor_1_3 = tf.Variable(5 , dtype=tf.float32)

In [11]:
print(tensor_1_1)
print(tensor_1_2)
print(tensor_1_3)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello World!'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>


In [13]:
add_1 = tf.add(tensor_1_2 , tensor_1_2)
print(add_1)
add2 = tensor_1_3 + tensor_1_3
print(add2)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(10.0, shape=(), dtype=float32)


In [14]:
cast = tf.cast(tensor_1_2 , dtype=tf.float32)

In [15]:
cast

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [16]:
tensor_1_2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

In [17]:
mul_1 = tf.multiply(tensor_1_2 , tensor_1_2)
print(mul_1)
mul_2 = tensor_1_3 * tensor_1_3
print(mul_2)

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(25.0, shape=(), dtype=float32)


In [21]:
print("Value of multipication : ",mul_1.numpy())
print("Value of multipication : ",mul_2.numpy())

Value of multipication :  25
Value of multipication :  25.0


**Two** Dimensional Tensor

In [23]:
tensor_2_1 = tf.Variable(np.array([[1,2] , [3,4]]) , dtype = tf.float32)
print(tensor_2_1)
tensor_2_2 = tf.Variable(np.arange(1,5,1).reshape((2,2)))
print(tensor_2_2)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>


In [25]:
# tensor_2_3 = tf.Variable([1,2,3,4] , shape=(2,2) ) 
#The initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).
tensor_2_3 = tf.constant([1,2,3,4] , shape=(2,2) ) 
print("Value of this constant is : ",tensor_2_3.numpy())
print("Shape : ",tensor_2_3.shape)
print(tensor_2_3)

Value of this constant is :  [[1 2]
 [3 4]]
Shape :  (2, 2)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [27]:
print(tf.multiply(tensor_2_1 , tensor_2_1))
print(tf.matmul(tensor_2_1 , tensor_2_1))

tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 7. 10.]
 [15. 22.]], shape=(2, 2), dtype=float32)


In [29]:
tensor_2_4 = tf.Variable(np.arange(1,7).reshape((2,3)))
print(tensor_2_4)
tensor_2_5 = tf.Variable(np.arange(1,7).reshape((3 , 2)))
print(tensor_2_5)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
<tf.Variable 'Variable:0' shape=(3, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>


In [32]:
mul_1 = tf.multiply(tensor_2_4 , tensor_2_4)
print(mul_1)
#mul2 = tf.multiply(tensor_2_4 , tensor_2_5) Incompatible shapes: [2,3] vs. [3,2] [Op:Mul]
#mul_2 = tf.matmul(tensor_2_4 , tensor_2_4) Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul]
mul_2 = tf.matmul(tensor_2_4 , tensor_2_5)  #(2 * 3) x (3 * 2) -> (2 * 2)
print(mul_2)

tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int64)


In [34]:
print(tf.cast(tf.square(tensor_2_2) , dtype=tf.float32))

tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)


**MultiDimentional Tensors**

In [40]:
tensor_3_1 = tf.Variable(tf.random_normal_initializer()((3,3,3)))
print("Shape : ",tensor_3_1.shape)
print("Data : ",tensor_3_1.numpy())
print("Total dim : ",tensor_3_1.numpy().ndim)

Shape :  (3, 3, 3)
Data :  [[[ 0.06295992 -0.07040277  0.03407536]
  [ 0.07279637  0.02813909 -0.04284434]
  [ 0.0304318  -0.07000867  0.03555426]]

 [[-0.05636443 -0.00230877  0.03352878]
  [ 0.01530375 -0.05590751  0.0254896 ]
  [-0.13223837  0.00683732 -0.0305792 ]]

 [[ 0.00015421  0.03119364 -0.02905964]
  [ 0.03845777 -0.05025832  0.04858482]
  [-0.00689838 -0.05511628 -0.00380394]]]
Total dim :  3


In [39]:
tensor_4_1 = tf.Variable(tf.zeros_initializer()((2,2,2,2)))
print("Shape : ",tensor_4_1.shape)
print("Data : ",tensor_4_1.numpy())
print("Total dim : ",tensor_4_1.numpy().ndim)

Shape :  (2, 2, 2, 2)
Data :  [[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
Total dim :  4
