In [ ]:
import tensorflow as tf
print("Version of tensorflow is : ",tf.__version__)
import numpy as np
import random

In [2]:
xs = np.arange(-6,7,1).astype(np.float32)
ys = (xs * 2) + 1

In [34]:
w = tf.Variable(random.random() , trainable=True )
b = tf.Variable(random.random() , trainable= True)
learning_rate = 0.001

In [28]:
def LossFunc(y_pred , y_true):
    return tf.abs(y_pred - y_true)

In [44]:
def fit_data(x , y):
    with tf.GradientTape(persistent=True) as tape:
        pred = w * x + b
        loss = LossFunc(pred , y)
    w_grad = tape.gradient(loss , w)
    b_grad = tape.gradient(loss , b)

    w.assign_sub(w_grad * learning_rate)
    b.assign_sub(b_grad * learning_rate)

In [45]:
for _ in range(500):
    fit_data(xs , ys)

In [46]:
w

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9743891>

In [47]:
b

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.9992402>

In [48]:
def prediction(num):
    return tf.multiply(num , w) + b

In [50]:
prediction(100.0)

<tf.Tensor: shape=(), dtype=float32, numpy=198.43814>

In [51]:
prediction(10.)

<tf.Tensor: shape=(), dtype=float32, numpy=20.743132>

In [53]:
prediction(np.arange(10,26,5))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([20.743132, 30.615078, 40.487022, 50.358967], dtype=float32)>